### ISSUE TITLE
24-hour format only

### ISSUE THREAD

**Issue by Dancopy** [bensoftde/smartmirror#1]
Hi Ben! I was interested in your watch but, I have some questions:
1) Is it possible to always leave in 24-hour format? (or delete the decimal mode)
2) Is it possible to change the font format of the text? (like here, for example: https://www.youtube.com/watch?v=gZbftQNrMn4 at time 0:08)
3) Do you have other projects with this type of matrix panel?
PS. All the matrix is lit and the text Leds are off; how can this be reversed in code?  Thank you very much

**Comment by bengelhaupt** [comment]
Hello,

1. Yes, just define `DEFAULT_CLOCK_TYPE_DECIMAL` as `false`
2. Just redefine the `symbols[]` array with the font you like. But mind that there are a few smaller versions of some symbols defined in the non-printable area of the ASCII code (0-32). Adjust the offsets accordingly.
3. I think [the underlying library I use has a `reverse()` function](https://github.com/Seeed-Studio/Ultrathin_LED_Matrix) to invert all pixels, which might help you with that.

I hope I could help you and sorry for the late reply.

Sincerely, Ben

**Comment by Dancopy** [comment]
Hi Ben! First, thanks for the answers;
About question 3, I saw this in the library:

delay(1500);
matrix.reverse();
delay(1500);
matrix.reverse();
matrix.clear();

Sorry for my ignorance but, should I put it like this in your sketch? Thank you one more time

**Comment by bengelhaupt** [comment]
For things like this I recommend having a look at the [implementation](https://github.com/Seeed-Studio/Ultrathin_LED_Matrix/blob/master/LEDMatrix.cpp) to understand how things work. Your code would reverse twice - without any effect.
Calling `reverse()` once after `begin()` in `setup()` should do the trick if I'm not wrong.
